#ifndef MOON_LOG_HH
#define MOON_LOG_HH

#include "soil/Log.hh"

#define MOON_LOG_INIT(x) SOIL_LOG_INIT(x)

#define MOON_TRACE SOIL_TRACE
#define MOON_DEBUG SOIL_DEBUG
#define MOON_INFO  SOIL_INFO
#define MOON_WARNING SOIL_WARNING
#define MOON_ERROR SOIL_ERROR
#define MOON_FATAL SOIL_FATAL
#define MOON_PDU SOIL_PDU
#define MOON_CUSTOM SOIL_CUSTOM


#endif

